### ISSUE TITLE
Just wanted to say thanks for this! Beautiful :) and is it possible to remove Himawari logos with himawari.js?

### ISSUE THREAD

**Issue by altosaar** [KYDronePilot/SpaceEye#18]
Just noticed the Himawari images have logos, but they don't on https://github.com/jakiestfu/himawari.js 

No worries if it's a hassle!!

**Comment by KYDronePilot** [comment]
Glad you like it!

I took a look at `himawari.js` and it looks like they are sourcing their imagery from Japan's National Institute of Information and Communications Technology (NICT), whereas SpaceEye uses the Regional and Mesoscale Meteorology Branch (RAMMB) of NOAA.

I would like to stick with RAMMB for the time being because:

- They provide GeoColor images (a composite of different channels captured by the satellite), where NICT only provides visible light images.
- The NICT servers are located in Japan, further away from my primary user-base (US). I've also experienced some issues not being able to connect to them myself.

That said, I should be able to implement a feature that overlays the logo with a black box to get rid of it.

**Comment by altosaar** [comment]
Great to know, thanks so much!! 

Fascinating to learn about geocolor vs visible light.

 Aren't the GOES-East images GeoColor as well, or are visible light images used from there? https://www.star.nesdis.noaa.gov/GOES/conus.php?sat=G16

**Comment by KYDronePilot** [comment]
Yep, as well as GOES-West. It's an exclusive image type made by NOAA/RAMMB (more info can be found [here](https://www.star.nesdis.noaa.gov/GOES/documents/QuickGuide_CIRA_Geocolor_20171019.pdf)). I like how it looks at night, with the infrared clouds and superimposed city lights. I'd still like to add the option to choose between visible and GeoColor in the future though.

**Comment by KYDronePilot** [comment]
The Himawari-8 view has been switched to a new SpaceEye-specific source that doesn't have the logo. If you're running the latest version, the status icon should now also say when the image was taken and state whether the view is in "backup mode" (images from a previous day are distributed if an up-to-date one can't be obtained).
