### ISSUE TITLE
Desktop stayed the same

### ISSUE THREAD

**Issue by SeaMac** [KYDronePilot/SpaceEye#26]
I had high hopes for this APP. I downloaded the version from the Mac Store and opened it. The Space Eye Icon showed up in the menu bar but my desktop picture NEVER Changed even when I repeatedly clicked the eye Icon. There was no apparent way to choose any source or change any selections. I even looked in the Control Panel under Desktop Picture and there was nothing New in there, either. It does NOTHING: so I uninstalled it.

Mac OS X 10.13.6 / Mac Pro (Mid 2012) /  16 GB 1333 MHz DDR3 of RAM

**Comment by KYDronePilot** [comment]
First, thank you for reporting the issue.

I believe this is because Mac App Store builds of SpaceEye don't work on older versions of OS X for some reason. I just tested the Mac App Store version on an old MacBook running 10.11.6 and only briefly saw the toolbar icon before it crashed.

Try installing SpaceEye from the `.dmg` file in the [latest GitHub release](https://github.com/KYDronePilot/SpaceEye/releases/tag/v1.2.1). I tested this on OS X 10.11.6 and everything worked as expected. When you click on the icon in the toolbar, the app should open a window right below it where you can select a view.

The Mac App Store builds of Electron js (which SpaceEye is built on) have some issues... I'm guessing they are using macOS features not available in earlier OS X versions.

**Comment by SeaMac** [comment]
That fixed it, Thank you! 
Added a Note about the problem on the Link Page for "SpaceEye" on my site! 
 https://softwaresanta.com/sssmf/index.php/topic,6152.0.html
